### ISSUE TITLE
 weight download

### ISSUE THREAD

**Issue by zwhus** [Q-MM/PureMM#2]
Error: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. How to solve it?

**Comment by PeterMao11** [comment]
> Error: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access. How to solve it?

you can download weight from huggingface

https://huggingface.co/Q-MM/PureMM/tree/main
