### ISSUE TITLE
What is the required conda environment for this code? thanks!

### ISSUE THREAD

**Issue by Leon1207** [Q-MM/PureMM#3]

**Comment by PeterMao11** [comment]
> _No description provided._

conda create -n puremm python=3.10 -y
conda activate puremm
pip install -r requirements.txt

**Comment by Leon1207** [comment]
Thanks for your reply. I have another question, how can I get the file format_mme_bench_v1.2.json from MME bench?

**Comment by aprilehannibal** [comment]
> Thanks for your reply. I have another question, how can I get the file format_mme_bench_v1.2.json from MME bench?

I have uploaded the file at here. https://github.com/Q-MM/PureMM/blob/main/eval/format_mme_bench_v1.2.json
You should modified the mme folder path with your own path to use it.

**Comment by Leon1207** [comment]
Thanks for your work. But when I tested a random image with the prompt in MME benchmark, I got the rubbish result. I have made sure that the model weights are loaded correctly, do you have any advice to solve it?
![image](https://github.com/Q-MM/PureMM/assets/60539679/6702cba4-0925-415c-81d7-86140bc766b0)

**Comment by aprilehannibal** [comment]
Is the output proper when you test with the mme images?



---Original---
From: ***@***.***&gt;
Date: Fri, Jan 19, 2024 21:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Q-MM/PureMM] What is the required conda environment for thiscode? thanks! (Issue #3)




 
Thanks for your work. But when I tested a random image with the prompt in MME benchmark, I got the rubbish result. I have made sure that the model weights are loaded correctly, do you have any advice to solve it?
 image.png (view on web)
